ALTER TABLE refresh_tokens
  ALTER COLUMN expires_at TYPE TIMESTAMPTZ,
  ALTER COLUMN created_at TYPE TIMESTAMPTZ,
  ALTER COLUMN used_at TYPE TIMESTAMPTZ;

ALTER TABLE cart_items
  ALTER COLUMN created_at TYPE TIMESTAMPTZ,
  ALTER COLUMN updated_at TYPE TIMESTAMPTZ;

ALTER TABLE addresses
  ALTER COLUMN created_at TYPE TIMESTAMPTZ,
  ALTER COLUMN updated_at TYPE TIMESTAMPTZ;

DROP INDEX IF EXISTS idx_refresh_tokens_token_hash;
